Repository CMSgov/dpc-app, pull requests merged in 2019-07, with the labels that each got.

#123 Modified Jobs to Require The Right Organization
  dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/AggregationEngineTest.java
  dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/BatchAggregationEngineTest.java
  dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/EncryptingAggregationEngineTest.java
  dpc-api/src/main/java/gov/cms/dpc/api/auth/OrganizationPrincipal.java
  dpc-api/src/main/java/gov/cms/dpc/api/auth/StaticAuthFilter.java
  dpc-api/src/main/java/gov/cms/dpc/api/auth/StaticAuthenticator.java
  dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractGroupResource.java
  dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractJobResource.java
  dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java
  dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/JobResource.java
  dpc-api/src/test/java/gov/cms/dpc/api/APITestHelpers.java
  dpc-api/src/test/java/gov/cms/dpc/api/FHIRSubmissionTest.java
  dpc-api/src/test/java/gov/cms/dpc/api/resources/JobResourceTest.java
  dpc-attribution/src/main/resources/queue_migrations.xml
  dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobModel.java
  dpc-queue/src/test/java/gov/cms/dpc/queue/QueueTest.java
  dpc-queue/src/test/java/gov/cms/dpc/queue/models/JobModelTest.java
Labels: enhancement

#148 Update developer documentation and fix website
  dpc-web/app/controllers/dpc_registrations_controller.rb
  dpc-web/app/views/docs/reference.html.erb
  dpc-web/app/views/docs/reference.md
  dpc-web/app/views/layouts/docs.html.erb
  ig/ig.json
  ig/source/pages/_includes/dpc-profile-patient-intro.md
  ig/source/pages/_includes/dpc-profile-practitioner-intro.md
  ig/source/resources/implementationguide/cms-dpc-ig.xml
  ig/source/resources/patient/DPC-sample-patient.json
  ig/source/resources/practitioner/DPC-sample-practitioner.json
Labels: bug, enhancement

#151 Added Google Analytics
  dpc-web/app/views/shared/_google-analytics.html.erb
  dpc-web/app/views/shared/_head.html.erb
  ig/framework/_includes/header.html
Labels: enhancement

#157 Made Changes to Developer Documentation
  dpc-web/app/views/pages/reference.md
Labels: enhancement

#166 check if close navbar button exists before adding a listener
  dpc-web/app/assets/javascripts/components/navbar.js
Labels: bug
